alina-gh-35 37
spbu-math-cs/topic-keeper pull request #48
Opened 2023-11-12 11:34 UTC by KAlina28

2023-11-12 13:17 UTC, IskanderSabirov commented on src/flow/main.go
> +	//sendMessage(username, reply)
лучше убрать комментарий

2023-11-12 13:20 UTC, IskanderSabirov commented on src/flow/main.go
> +			Description: "Приостановка оновлений в боте",
получения обновлений*

2023-11-12 13:21 UTC, IskanderSabirov requested changes
В целом все норм, кажется

2023-11-12 13:21 UTC, IskanderSabirov commented on src/flow/main.go
> +			Description: "Возобновление работы бота",
Возобновление получений обновлений*

2023-11-13 18:15 UTC, askalt approved these changes

2023-11-13 18:31 UTC, merged